# Generated by Django 5.0.6 on 2024-07-11 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='autor',
            new_name='author',
        ),
    ]
